services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - app-vendor:/var/www/html/vendor
    depends_on:
      - app
  app:
    build: 
      context: "."
      dockerfile: "./docker/app/Dockerfile"
    volumes:
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./templates:/var/www/html/templates
      - app-vendor:/var/www/html/vendor
volumes:
  app-vendor:
    driver: local