<?php
define('TEST_MODE', false); // Use true for development
define('CRAUTO_PASS_MIN_LENGTH', 12);
define('CRAUTO_LDAP_URL', 'ldap://ldap1.sso.local');
define('CRAUTO_LDAP_BIND_DN', 'cn=Directory Manager');
define('CRAUTO_LDAP_PASSWORD', 'secret1');
define('CRAUTO_LDAP_STARTTLS', true);
define('CRAUTO_LDAP_USERS_DN', 'ou=People,dc=sso,dc=local');
define('CRAUTO_LDAP_GROUPS_DN', 'ou=Groups,dc=sso,dc=local');
define('CRAUTO_LDAP_INVITES_DN', 'ou=Invites,dc=sso,dc=local');
define('CRAUTO_OIDC_ISSUER', 'https://wso2.sso.local:9443/oauth2/oidcdiscovery');
define('CRAUTO_OIDC_CLIENT_ID', 'crauto'); // This is useless
define('CRAUTO_OIDC_CLIENT_KEY', '3VEQd6YM2a9qXtCGQJs8nGfm2Dsa'); // This is important (generated by WSO2 IS)
define('CRAUTO_OIDC_CLIENT_SECRET', 'Fd4BxUyaYYlByimKfAwv6_rDyl0a'); // This is even more important (generated by WSO2 IS)
// Also, you shouldn't commit the secret (and possibly the key) in a public repo. These are used only in development,
// production key and secret are obviously different.
define('VERIFY_CERTIFICATES', true); // Set to false for development with self-signed certificates
define('CRAUTO_URL', 'http://[::1]:8200');
define('CRAUTO_DEBUG_ALWAYS_REFRESH', false); // Set to true to use the refresh token to get a new id token on each request
define('CRAUTO_IMAGE_URL', 'http://[::1]:8300');
define('CRAUTO_HOME_PAGE_SERVICES', [
	['Description description description', 'https://url.example.com', 'something'],
	['Description', 'https://url.example.com'],
	['Description without link']
]);
