<?php
const TEST_MODE = true; // Use false for production
const TEST_MODE_SSO = 1; // Use 1, 2 or 3 to log in as different test accounts, only used if TEST_MODE is true
const CRAUTO_PASS_MIN_LENGTH = 12;
const CRAUTO_SIR_TMP_DIR_CLEANUP = 30;
const CRAUTO_LDAP_URL = 'ldap://ldap1.sso.local';
const CRAUTO_LDAP_BIND_DN = 'cn=Directory Manager';
const CRAUTO_LDAP_PASSWORD = 'secret1';
const CRAUTO_LDAP_STARTTLS = true;
const CRAUTO_LDAP_USERS_DN = 'ou=People,dc=example,dc=test';
const CRAUTO_LDAP_GROUPS_DN = 'ou=Groups,dc=example,dc=test';
const CRAUTO_LDAP_INVITES_DN = 'ou=Invites,dc=example,dc=test';
const CRAUTO_OIDC_ISSUER = 'https://sso.example/oauth2/oidcdiscovery';
const CRAUTO_OIDC_CLIENT_KEY = '3VEQd6YM2a9qXtCGQJs8nGfm2Dsa'; // This is important (generated by WSO2 IS)
const CRAUTO_OIDC_CLIENT_SECRET = 'Fd4BxUyaYYlByimKfAwv6_rDyl0a'; // This is even more important (generated by WSO2 IS)
// Also, you shouldn't commit the secret (and possibly the key) in a public repo. These are used only in development,
// production key and secret are obviously different.
const VERIFY_CERTIFICATES = true; // Set to false for development with self-signed certificates
const CRAUTO_URL = 'http://[::1]:8200';
const CRAUTO_DEBUG_ALWAYS_REFRESH = false; // Set to true to use the refresh token to get a new id token on each request
const CRAUTO_DEFAULT_GROUPS = 'Test,Cloud,Admin';
const CRAUTO_WEBSITE_IGNORE_GROUPS = 'Docenti,Foo,Bar';
const CRAUTO_HOME_PAGE_SERVICES = [
	['Description description description', 'https://url.example.com', 'something'],
	['Description', 'https://url.example.com'],
	['Description without link']
];
