name: CI
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"

      - name: Linting
        uses: php-actions/composer@v6
        with:
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"
          command: lint

      - name: Create config
        run: cp config/config-example.php config/config.php

      - name: Run tests
        uses: php-actions/composer@v6
        with:
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"
          command: test
