name: CI
on: [push, pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1', 'latest']

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          # If you use the PHPUnit action, uncomment this and comment php_extensions
          # args: --ignore-platform-reqs
          php_extensions: ldap mbstring json sqlite3
          php_version: "${{ matrix.php }}"

      - name: Linting
        run: composer lint

      - name: Create config
        run: cp config/config-example.php config/config.php

      - name: Run tests
        run: composer test
